### ISSUE TITLE
Error specifying fieldmaps using aas_addsubject

### ISSUE THREAD

**Issue by Aahana1** [automaticanalysis/automaticanalysis#201]
Hello,
I’m trying to specify fieldmaps using aas_addsubject with the following:
`aap = aas_addsubject(aap, 'sub-01', ‘sub-identifier, ’fieldmaps',[11 12]);`

Tasklist:
` <module><name>aamod_get_dicom_fieldmap</name></module>             
 <module><name>aamod_convert_fieldmaps</name></module>`
     
However, the fieldmap modules in the task list do not get executed. 
1. Could you please provide an example of the correct way to do this?
2. Is it necessary that other functional series from the scan also be specified at the same time?

Thank you.
Aahana

**Comment by tiborauer** [comment]
Hi Aahana1,

I can see several issues with your script, but it is hard to judge without seeing the whole.
Anyway, you can find some fitting examples here: [UMS](https://github.com/automaticanalysis/automaticanalysis/blob/master/examples/cbu/aa_user_fmri.m) and [tasklist](https://github.com/automaticanalysis/automaticanalysis/blob/master/examples/cbu/aap_tasklist_fmri.xml). I hope they help.
Let me know how you proceed.

Tibor

**Comment by tiborauer** [comment]
Hi @Aahana1, did you have any luck with the examples? I have also realised that the main issue might be related to your second question. Yes, you do need functional (or diffusion) series, because fieldmaps are interpreted only in relation with them.

**Comment by Aahana1** [comment]
Hi @tiborauer, I've tried implementing the script with fieldmaps + functionals and also fieldmaps + diffusion series but didn't have much luck with either. The problem might also be due to differences in the internal file structures that I'm working with. I haven't had a chance to work further on these lately, I will update you if something works on my end once I get back to it. 
Thanks for your help.
Aahana

**Comment by tiborauer** [comment]
Hi @Aahana,

Let me know if you need further help. Regarding file structure, you can use the example demo data <https://files.osf.io/v1/resources/umhtq/providers/osfstorage/5b7465680b87a00018c6a76f>  and the corresponding script <https://github.com/automaticanalysis/automaticanalysis/blob/master/examples/aa_user_demo.m> . Unlike the example in my previous message, this one is not with fieldmap, though.

The main pint is that you do not have to accommodate your file structure to aa, because you can tell aa about your file structure using the aap_parameterset. The most corresponding field are:

*	rawdatadir desc: Directories to find raw MRI data
*	subjectoutputformat: sprintf formatting string to get subject directory from identifyer
*	seriesoutputformat: sprintf formatting string to get series directory from number (e.g. Series_%03d*). It is only relevant if you organise your DICOM images into subfolders according to series.
*	protocol_fieldmap, protocol_structural, protocol_t2: string patterns to autoidentify protocols for fieldmap, structural, and T2 (the protocol DICOM tag varies among vendors: SeriesDescription for GE and Philips, and ProtocolName for Siemens)
*	dicomfilter: string pattern to filter DICOM images (e.g. *.dcm)

 

Vale,

Tibor

 

Auer, Tibor (Ph '99)

**Comment by Aahana1** [comment]
Hi @tiborauer ,
I think part of my fieldmap issue might be because of the following. 
This is the output from aamod_autoidentifyseries_timtrio.m which suggests that aa is able to find the field map and diffusion files. 

Series 11 (SpinEchoFieldMap_AP_2p0mm ) with 3 dicom files
Series 12 (SpinEchoFieldMap_PA_2p0mm ) with 3 dicom files
Series 21 (ep2d_diff_dbsi_99_iso2_wholebrain ) with 6930 dicom files
Series 22 (ep2d_diff_dbsi_99_iso2_wholebrain_AP) with 70 dicom files
Series 23 (ep2d_diff_dbsi_99_iso2_wholebrain_PA) with 70 dicom files

I have two different tags ’SpinEchoFieldMap_AP_2p0mm’ and ‘SpinEchoFieldMap_PA_2p0mm’ for fieldmaps and I'm assuming aa is looking for 1 generic tag for the protocol.
I’m not sure how to accommodate for this in setting the aap.directory_conventions.protocol_fieldmap

On a different note, I tried running my code with your new PR #202 since it also had some changes to aamod_convert_filedmaps.m.

I noticed that the end statement in line 45 might have been misplaced. When the if statement in line 24 is false, Vfm never specified. This might not have much to do with my issue but just thought i'd let you know.

Thanks,
Aahana

**Comment by tiborauer** [comment]
You do not have to specify the full name of the protocol, because aa uses a pattern search. However, you have to make sure that the pattern you specify is distinguishing enough. So I would suggest `"SpinEchoFieldMap" `as `protocol_fieldmap`.
Another issue is that topup/opposing PE is not implemented for fMRI but for diffusion only in aa. It is something I am working on, but I have nothing to share at the moment.

Thank you for your test and notice for PR #202. I will update the code ASAP.

**Comment by tiborauer** [comment]
Hi, @Aahana1, I have updated the PR #202

**Comment by tiborauer** [comment]
@Aahana1, Do you still have the issue or shall we close it?

**Comment by Aahana1** [comment]
Hi @tiborauer , I've closed the issue for now. Thank you.
