### ISSUE TITLE
Help with aamod_CoSMoMVPA

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#210]
Hello all,

Been trying to use aamod_CoSMoMVPA to do some spotlight analysis
without much success. 

The module does some kind of bizarre cellfun parsing, including an 
"attr" tag on the input stream which I've never seen before and can't
find any documentation about.

Has anybody used this? If so, can you explain how I set up the input?

Regards,
Mike

**Comment by tiborauer** [comment]
This "attr" tag is just a dummy attribute to make sure that it can be combined with eventual new input streams also with structure (which may be required if connected).

There is no example and documentation for CoSMoMVPA, because there is no open data for it. The module has been developed for PhD projects, and one of them will make data and scripts openly available. It is quite nicely documented. That will be our documentation, too.

As a 'teaser': inputs have to be added using aas_renamestream. Here, a separate pipeline was required because each run had to be added separately, so that it could be modelled in RSA.

```
% Add grey matter brain mask to aamod_CoSMoMVPA to perform RSA. See aamod_CoSMoMVPA.xml header for description.
aap = aas_renamestream(aap,sprintf('aamod_CoSMoMVPA_%05d',b),'append','aamod_mask_fromsegment_00001.normalised_grey_mask','input');
            
% Add spm.mat files for all participants to aamod_CoSMoMVPA. Calculation based on RSA_1_preprocess_tasklist, modality, and run number.
aap = aas_renamestream(aap,'aamod_CoSMoMVPA_00001,'append','aamod_firstlevel_contrasts_00001.firstlevel_spm:isessential-0','input');            
% Add t-maps for all participants to aamod_CoSMoMVPA. Calculation based on RSA_1_preprocess_tasklist, modality, and run number.
aap = aas_renamestream(aap,aamod_CoSMoMVPA_00001,'append','aamod_firstlevel_contrasts_00001.firstlevel_spmts:isessential-0','input');
```

**Comment by jones-michael-s** [comment]
Thanks for the info.

I'll keep trying to make progress with this.
