### ISSUE TITLE
aamod_secondlevel_contrasts unexpected behaviour

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#217]
Hello all,

Ran into some unexpected behaviour from aamod_secondlevel_contrasts.

Consider this tasklist excerpt:

`<module><name>aamod_secondlevel_model</name></module> `
`<module><name>aamod_secondlevel_contrasts</name></module>`
`<module><name>aamod_secondlevel_threshold</name>...</module>`
`<module><name>aamod_secondlevel_threshold</name>...</module>`

Yes, aamod_secondlevel_threshold appears twice -- I run the first using UNC 0.001 and the second 0.05 FWE and have omitted the parameter settings xml code (represented by the ...) for clarity.

Running aa gives the expected stream verification on startup:

![stream_verify0](https://user-images.githubusercontent.com/25826038/93022765-81442f00-f5b0-11ea-918a-7ae7c21dea55.jpg)

However, if I remove aamod_secondlevel_contrasts  from the tasklist (I will explain why I tried this in a moment), here is the stream verification I get on startup:

![stream_verify1](https://user-images.githubusercontent.com/25826038/93022704-33c7c200-f5b0-11ea-8f53-58594146f86f.jpg)

Two unexpected things have happened.

1) aamod_secondlevel_threshold is now taking stream secondlevel_spm from aamod_secondlevel_model not aamod_secondlevel_contrasts. 

2) the second instance of aamod_secondlevel_threshold no longer appears in the stream list.

Removing aamod_secondlevel_contrasts probably seems silly, but where this really happened was switching between running this tasklist using PCT (for speed) and localsingle (for debugging) in a branched tasklist. It appears the scheduler runs modules in a different order under PCT than under localsingle. I eventually wound up with all of my secondlevel_thresholds modules having completed before the secondlevel_contrasts modules did, which seemed impossible. So I started testing whether aamod_secondlevel_contrasts is needed at all. Apparently it is not.

The questions become:

1) What, exactly, does aamod_secondlevel_contrasts do? Yes, it modifies secondlevel_spm (which aamod_secondlevel_threshold takes as input), but aamod_secondlevel_threshold doesn't seem to care. Should it?

2) Why does the scheduler ignore the second instance of aamod_secondlevel_threshold if aamod_secondlevel_contrasts is not included in the tasklist?

Is this a) weird but harmless or b) something we need to look into?

**Comment by tiborauer** [comment]
Have you checked the "finished" aamod_secondlevel_threshold? I bet it did not produce any image.

0. Everything I write here also applies to the firstlevel modules because they use similar 'machinery'.

1. The contrast modules do not only modify the SPM structure but also creates the contrast estimates (con and ess images in the *level_spmts and *level_spmfs streams), which they register in the SPM structure. The thresholding modules, then, calculate the inference (spmT and spmF images) on the contrast estimates and thresholds the inferences. If you look at the module headers (XMLs), you will see that both the firstlevel_spmts and the firstlevel_spmfs streams are optional because you can do either T or F contrast.
If you take out the contrast module, then the thresholding module retrieves the SPM with no contrast estimate (image or in the SPM structure), so it processes no inference and finishes. I guess we can make it crash if there is no contrast available, but you are never expected to have a thresholding module without a contrast module.

2. I do not know much about the PCT engine, but I remember it uses some elaborated approach to run all possible modules. It may explain why it behaves differently than using localsingle.

+1. If you want to use multiple thresholding on the same contrast estimates, then I suggest using branching, which is more in line with aa's architecture.

++1. Have you ever tried using qsub or qsub_nonDCS? AFAIR, qsub is not an option for you (why?), but qsub_nonDCS should work if you have MATLAB licenses available for each worker node (e.g. Campus-wide licensing) and you use Torque/SLURM/SoGE/LSF scheduler.

**Comment by jones-michael-s** [comment]
Hi Tibor,

Thanks for the quick reply.

> If you take out the contrast module, then the thresholding module retrieves the SPM with no contrast estimate (image or in the SPM structure), so it processes no inference and finishes. I guess we can make it crash if there is no contrast available, but you are never expected to have a thresholding module without a contrast module.

I will explore this in a fresh analysis and report back. I thought I saw secondlevel_threshold generating images and done flags even though secondlevel_constrast had not run but I should double-check this. Perhaps it will simply crash (fingers crossed!).

> ++1. Have you ever tried using qsub or qsub_nonDCS? ...

We tried to run aa on our cluster (using both qsub and qsub_nonDCS) for about two years and eventually gave up. Jobs would queue and never run, jobs would start and immediately die, individual modules (like smoothing) were taking as long as 12 _hours_ to complete. This wasn't aa's fault -- I could reproduce some of these problems in a five line mfile. Unfortunately, fixing the Matlab installation wasn't a priority for their sysadmin. So we bought a fast Mac with a big disk and never looked back. aa is superb with the PCT. Lightning fast, (mostly) crash free, and you get all of the diagnostic images. I only wish I could get those two years of my life back...

**Comment by jones-michael-s** [comment]
Follow-up: If aamod_secondlevel_contrasts is omitted from the tasklist, aamod_secondlevel_threshold neither crashes nor generates any thresholded results. Which I suppose is exactly what it should do.

Since the manner in which I triggered the unexpected behavior was rather pathological (run part of an analysis under localsingle then run part under PCT), I don't think it's necessary to pursue this further. Closing issue...
