### ISSUE TITLE
aaq_matlab_pct & global variables

### ISSUE THREAD

**Issue by hhentschke** [automaticanalysis/automaticanalysis#219]
I've been unable to run any of the demo scripts anywhere near to completion using the matlab_pct queue processor. Please correct me if I'm wrong, but I think the larger issue here is that the spmd construct [grates with global variables](https://de.mathworks.com/help/parallel-computing/execute-simultaneously-on-multiple-data-sets.html).
Concretely, the workers addressed within the `spmd...end` block don't automatically have access to global variable `aacache` as exists in the client workspace, and hence produce all kinds of errors where its fields are accessed via `aas_cache_get`, e.g. in line 54 of aamod_segment8.m: `[junk, SPMtool] = aas_cache_get(aap,'spm');`.

I think I found a solution - it's essentially a one-liner using `parfevalOnAll` to assign `aacache` to homonymous 'global' variables in the workspaces of each worker before the spmd code block. Happy to issue a pull request if this is deemed helpful (and the problem is not due to some oversight on my side).

**Comment by tiborauer** [comment]
Hi @hhentschke, as we discussed last time, it is, indeed the issue. However, I am not sure you need parfevalOnAll rather than simply add the `aachache` to the struct `aaworker`, which is/can be an argument of the jobs. See [the corresponding commit](https://github.com/automaticanalysis/automaticanalysis/commit/4162fd48e50eb56abf00f255ba3d789fc28f839f#diff-5fe57c0d988d08e201c8e99e6622ecbec1a4bff90b55c366780a2740aac6ccde).

**Comment by hhentschke** [comment]
OK, thanks for the hint! You're right, adding `aacache` to to `obj.aaworker` does the trick, and in a simpler manner.
