### ISSUE TITLE
What does the ismodified tag mean?

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#220]
Could I trouble someone for a quick explanation of what the "ismodified" stream tag means?

I thought tagging an input stream ismodified=0 (i.e. false) means: "this stream is not modified by the module."

However, there are modules with an input stream tagged ismodified=0 that clearly modify the tagged stream. For example, aamod_smooth tags the epi input ismodified=0 and it obviously modifies the input epi.

There's also a few modules that explicitly tag an input stream ismodified=0 but the stream doesn't appear as an output stream (e.g. epi in aamod_tsdiffana). If an input stream doesn't appear as an output, then by definition it isn't modified, no?

I started grepping through the scheduler to figure this out, but the scheduler code is rather complex...

Thanks much,
Mike

**Comment by tiborauer** [comment]
ismodified generally means that the file in the input stream is not modified, so it is safe to link rather than copy from the source module. It, however, does not mean that the module does not create a new file a put it into the same stream.

**Comment by jones-michael-s** [comment]
So -- just to see if I understand this -- using aamod_smooth as an example, the input epi is considered "not modified" because aamod_smooth creates a _new_ file (ala a call to spm_smooth) which it assigns to the epi output stream. If it had instead _overwritten_ the input epi instead of creating a new file, then tagging the input epi as ismodified=0 would be an error.

Is that correct?

**Comment by tiborauer** [comment]
I am not sure whether it actually throws an error but it would go against the concept, yes.
If you take coregistration, for example, it overwrites the header in the original file, so there ismodified should be 1.

**Comment by jones-michael-s** [comment]
Yeah, I meant "error" as in "asking for trouble" :-)

In aamod_tsdiffana, could it be that the ismodified=0 tag on the epi is just some cut and paste that didn't get cleaned up (but is otherwise harmless)? I assume if a stream isn't listed in the output, then an ismodifed tag is moot.

**Comment by tiborauer** [comment]
ismodified tag is not about a between-module relationship, namely whether a module modifies a file created by another. 
- If ismodified = 0, it means it is safe to link the input from its source rather than copy it because it will not be modified, so the source of the link stored in the source module remains valid.
- If ismodified = 1, it means it is not safe to link the input because its editing would invalidate the source of the link stored in the source module.

In case of aamod_tsdiffana, the input is not modified but only read, so it is safe to link the epi from the source module.

On the other, we use hard links rather than symbolic links, which more like a copy.
https://github.com/automaticanalysis/automaticanalysis/blob/ca1dac635c693ac7c64868fd8f8fafeab44ef199/aa_engine/aas_retrieve_inputs_part2.m#L131-L135

**Comment by jones-michael-s** [comment]
Thanks -- that's helpful.
