### ISSUE TITLE
An error regarding Parallel Computing

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#334]
Dear all,

The machine has 8 cores.. When I ran PCT with the following settings:

```
aap.options.wheretoprocess='matlab_pct';
aap.directory_conventions.poolprofile = 'local';
aap.options.aaparallel.numberofworkers = 15;
```

At some point during my analysis, I ran into an "out of memory" error I don't have the exact error message, because I forgot to save it. But it was complaining about a specific worker (I think 14) and saying that the memory wasn't enough.

How should one decide what amount of number of workers to use? And is there a way to specify RAM to use? And what factors should I consider while deciding on the amount of RAM to allocate?

Finally, does AA allow GPU acceleration at all? And is there any plans of implementing GPU acceleration to this?

**Comment by jones-michael-s** [comment]
Hello @TamerGezici,

I have found using  numberofworkers ≤ (number-of-cores - 1) to give good aa performance in my work.

So on an 8 core machine I would try aap.options.aaparallel.numberofworkers = 7  or 6.

If you continue to have problems, you can also try aap.options.wheretoprocess='parpool' instead of 'matlab_pct'. This is a newer version of the parallel scheduler.

As far as I know, there isn't a way in aa to explicitly allocate RAM. Also, aa doesn't not currently use GPU acceleration, and I don't know if anyone is planning such a project.

Regards,
Mike

**Comment by tiborauer** [comment]
You can set options of parallel processing in
```
aap.options.aaparallel.numberofworkers % Requested number of workers
aap.options.aaparallel.memory % Requested amount of memory in GB
aap.options.aaparallel.walltime % Maximum amount of time (in hours)

```

The defaults are 8 workers, 4GB each, for 24 hours.

Using `local` cluster profile, it means that you need 8*4=32 GB just for the jobs. So it is likely that you run out of memory unless you have >48GB

**Comment by TamerGezici** [comment]
Ah I see. So having 16GB RAM, is it best to have only 2 workers? Or can I allocate less RAM per worker and allocate more workers? Would that make a difference?

What is the best configuration for 16GB RAM? Or is it even worth using parallel computing for this much RAM?

**Comment by tiborauer** [comment]
Sure you can have less memory per workers, however, I advise against <2GB because MATLAB only takes 1GB.

Ideally, you should know what resources your jobs require. If you do standard fMRI analysis (SPM only), then 2GB should work. Then you can have e.g. 6 workers, which would take 12GB. 4GB might be just enough for your OS and MATLAB with the as engine.
If it fails, try 4 workers.

**Comment by TamerGezici** [comment]
Thank you and Michael for your responses. I greatly appreciate it. Since I have received answers to my questions, I can close the issue now.
