### ISSUE TITLE
ENH - Garbagecollection exclude module

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#348]
Hi,

Is there a way to disable garbage collection for a specific module? Garbage collection causes problems when I use marsbar, which uses the SPM matrice SPM.xY.VY field to access smoothened files directory. Since the first level model copies files into the module while estimating a model, and garbage collection deletes those files, the files become inacessible.

P.S I know that marsbar has a solution for this, and I use it. But I think it is a little tricky to use that solution if you have unequal run counts. So, I thought it could be good to have a module exclusion options if need be? I can implement it myself and submit a PR if it doesn't exist.

**Comment by tiborauer** [comment]
Although you cannot exclude modules by name, there are several ways to control garbage collection. You can disable automatic default garbage collection by `aap.options.garbagecollection  = 0;` and run a manual one where you can specify some parameters: https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_engine/aas_garbagecollection.m#L7

`modulestoscan`
You can specify which module(s) in the pipeline you want to clean. Here you specify an array of numbers, which indicates the temporal position of the module(s) in the workflow (`{aap.tasklist.main.module.name}'`)

`permanencethreshold` 
Some modules have a setting called `permanenceofoutput`. For example https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_modules/aamod_firstlevel_model.xml#L11 These modules will be cleaned only if the `permanencethreshold` is set >= `permanenceofoutput`. It is 0 by default, so any modules with a non-zero `permanenceofoutput` will be excluded from the garbage collection. https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_engine/aas_garbagecollection.m#L125-L129

**Comment by TamerGezici** [comment]
Thanks for the explanation, what I don't understand is if `aamod_firstlevel_model` `permanenceofoutput` is 3 by default, why does garbage collection clear the smoothened files in the `aamod_firstlevel_model_*` directory when I run the default garbagecollection? I am talking about the duplicate files which are copied over to the module folder, not the smoothened files in aamod_smooth. 

Since it's 0, and the module is 3,  0 < 3 these files shouldn't have been deleted at all. I checked the `permanenceofoutput` for `aamod_smooth.xml`, which is also 2. So I'm confused.

At any case, I am assuming if I set the `permanenceofoutput` of the specific modulue in my `tasklist.xml` it should work. The question is, what number?

**Comment by tiborauer** [comment]
I am sorry for the confusion, but you must understand that aa handles input and output streams differently:

- Input streams are duplicates because they exist in their source module. Therefore, they are always deleted, if scanned.
- Output streams have special treatment, which can be controlled by the `permanenceofoutput`  parameter. 

As default (`permanenceofoutput =0`), all modules, including `aamod_smooth` and `aamod_firstlevel_model`, should retain their outputs (i.e., smoothed EPIs in `aamod_smooth` and model estimates in `aamod_firstlevel_model`) but their inputs (i.e. smoothed EPIs in `aamod_firstlevel_model`) are deleted.

If you want to keep inputs in `aamod_firstlevel_model`, you should specify `modulestoscan`, including only those modules you want to clean. You refer to modules by their temporal position of the module(s) in the workflow ({aap.tasklist.main.module.name}'). I.e., if your `aamod_firstlevel_model` is the 20th of 30 modules, then `modulestoscan = [1:19 21:30];`

**Comment by TamerGezici** [comment]
Sorry for the late reply. I was busy with other things.

So, if I exclude aamod_firstlevel_model from the array like I explain below, that module will not be deleted. But the rest of all modules left, do get deleted (at least that's what happened last time). Before running, I want to check if my approach is correct.

```
{aap.tasklist.main.module.name}'

ans =

  10×1 cell array

    {'aamod_structuralfromnifti'   }
    {'aamod_epifromnifti'          }
    {'aamod_tsdiffana'             }
    {'aamod_realign'               }
    {'aamod_slicetiming'           }
    {'aamod_coreg_extended'        }
    {'aamod_biascorrect_structural'}
    {'aamod_segment_structural'    }
    {'aamod_norm_write_epi'        }
    {'aamod_firstlevel_model'      }
```

The module I would like to keep is at position 10.

```
modules_to_scan =

     1     2     3     4     5     6     7     8     9
```

Here's a variable which stores which modules to scan for.

Function call:

`aas_garbagecollection(aap, 0, modules_to_scan, -1)`

This removes inputs for tsdiffana, realignment and normalization. However, as far as I understand coregisteration inputs will remain. To remove coreg inputs, do I need to modify the permanence of output parameter for slice timing?

**Comment by tiborauer** [comment]
If you say `actuallydelete = 0` (second parameter), then nothing will be deleted at all.
`modulestoscan` seems fine
You do not have to set `permanencethreshold` because it is `0` by default.

BTW, there might be a bug in 
https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_engine/aas_garbagecollection.m#L52-L53
The aim of this section  is to stop garbage collection for modelling. I am afraid this section should be
```matlab
ind = cell_index({aap.tasklist.main.module.name}, 'level');
if ind, modulestoscan=1:ind(1)-1; end
```

**Comment by TamerGezici** [comment]
I made actuallydelete=0 on purpose so things dont get actually deleted :) I was looking at garbage_collection.txt to see what was getting deleted.

**Comment by TamerGezici** [comment]
> If you say `actuallydelete = 0` (second parameter), then nothing will be deleted at all. `modulestoscan` seems fine You do not have to set `permanencethreshold` because it is `0` by default.
> 
> BTW, there might be a bug in
> 
> https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_engine/aas_garbagecollection.m#L52-L53
> 
> 
> The aim of this section is to stop garbage collection for modelling. I am afraid this section should be
> ```matlab
> ind = cell_index({aap.tasklist.main.module.name}, 'level');
> if ind, modulestoscan=1:ind(1)-1; end
> ```

Adding your change and running `aas_garbagecollection(aap,false);` yielded output of this:

https://gist.github.com/TamerGezici/aceb9795497da943b3210442f198cbc8

**Comment by tiborauer** [comment]
Looks good to me.

**Comment by TamerGezici** [comment]
Thanks a lot. I can commit this later if you want.

**Comment by tiborauer** [comment]
If it works, please!
