### ISSUE TITLE
ENH - Check reg processes each volume in a run seperately for 3D NIfTI 

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#356]
When you use 3D NIfTI, it does check reg for each 3D volume in the run. 

https://github.com/automaticanalysis/automaticanalysis/blob/b332aaec0c0654cdd144ddddead00b2aa4ea868d/aa_engine/aas_checkreg.m#L49

And I think this line is supposed to ensure a single volume goes through, however for 3D NIfTI your cell array `image` becomes like this, basically a cell array with all images inside it.

```
  'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_495.nii'
    'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_496.nii'
    'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_497.nii'
    'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_498.nii'
    'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_499.nii'
    'D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_coreg_extended_2_epi_00001\sub-01\discrB_run-02\rasub-01_ses-1_task-discrB_run-02_bold_500.nii'
```

I wanted to do some adjustment for 3D NIfTI, but I was not sure what image I should choose? The first, middle or last in the run? 

I guess for 4D NIfTI a single volume is chosen. I don't know what volume is chosen and on what ground, though.

Also let me mention that it goes into this function from here:

https://github.com/automaticanalysis/automaticanalysis/blob/b332aaec0c0654cdd144ddddead00b2aa4ea868d/aa_modules/aamod_coreg_extended_2.m#L173

The line below you can see that it does check reg for mEPIimg and then proceeds to do it for each image I think. Commenting that line out sorted the 3D NIfTI issue for me so I guess we can do something to do this loop to prevent this from happening.

**Comment by tiborauer** [comment]
The problem is that there is no simple generic solution for your case because some other streams also have multiple images for various reasons, and each must be checked.

The coreg_extended module can register multiple streams via a single one. In your case, it registers the epi stream via the meanepi. Because meanepi comes from epi, commenting out line 173 may not lose information. However, there are cases when the two streams have different modalities. Therefore, commenting line 173 is not a generic solution.
On the other hand there seems to be a bug in coreg_extended.

```matlab
        if ~isfield(aap.tasklist.currenttask.settings,'diagnostic') ||...
                    (~isstruct(aap.tasklist.currenttask.settings.diagnostic) && aap.tasklist.currenttask.settings.diagnostic) ||...
                    (isstruct(aap.tasklist.currenttask.settings.diagnostic) && isfield(aap.tasklist.currenttask.settings.diagnostic,'streamind') && m == aap.tasklist.currenttask.settings.diagnostic.streamind)
            aas_checkreg(aap,domain,cell2mat(varargin),mEPIimg,'structural');
            for m = 1:numel(mainstream)
                aas_checkreg(aap,domain,cell2mat(varargin),mainstream{m},'structural');
            end
        end
```

**Comment by tiborauer** [comment]
The problem is that there is no simple generic solution for your case because some other streams also have multiple images for various reasons, and each must be checked.

The coreg_extended module can register multiple streams via a single one. In your case, it registers the epi stream via the meanepi. Because meanepi comes from epi, commenting out line 173 may not lose information. However, there are cases when the two streams have different modalities. Therefore, commenting line 173 is not a generic solution.
On the other hand there seems to be a bug in coreg_extended, line 168-175, which should be
```matlab
        % Diagnostic stream
        if ~isfield(aap.tasklist.currenttask.settings,'diagnostic') ||
                    (~isstruct(aap.tasklist.currenttask.settings.diagnostic) && aap.tasklist.currenttask.settings.diagnostic) ||...
                    (isstruct(aap.tasklist.currenttask.settings.diagnostic) && isfield(aap.tasklist.currenttask.settings.diagnostic,'streamind') && aap.tasklist.currenttask.settings.diagnostic.streamind > -1)
            aas_checkreg(aap,domain,cell2mat(varargin),mEPIimg,'structural');
        end
        
        % Main streams
        for m = 1:numel(mainstream)
            if ~isfield(aap.tasklist.currenttask.settings,'diagnostic') ||
                        (~isstruct(aap.tasklist.currenttask.settings.diagnostic) && aap.tasklist.currenttask.settings.diagnostic) ||...
                        (isstruct(aap.tasklist.currenttask.settings.diagnostic) && isfield(aap.tasklist.currenttask.settings.diagnostic,'streamind') && aap.tasklist.currenttask.settings.diagnostic.streamind == m)
                aas_checkreg(aap,domain,cell2mat(varargin),mainstream{m},'structural');
            end
        end
```

Then the corresponding XML header file MUST contain:
```xml
            <diagnostic>
                <streamind desc='index of main output stream (i.e. image) to be reported, 0 means the diagnostic stream only'>1</streamind>
            </diagnostic> 

```

Finally, if you set `aap.tasksettings.aamod_coreg_extended_2_epi.diagnostic.streamind = 0;`, then the epi stream will be ignored. This solution would be generic.

**Comment by TamerGezici** [comment]
Yes exactly. I had been thinking if that if block could have been bugged. Let me try this and get back to you! Thanks a lot for helping.

**Comment by TamerGezici** [comment]
https://github.com/automaticanalysis/automaticanalysis/pull/357
