### ISSUE TITLE
ismodified flag confusion

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#394]
I am not sure why a module like `aamod_smooth `has the `ismodified` flag set to 0 (ie., see below)

https://github.com/automaticanalysis/automaticanalysis/blob/10b3425d2a99e294e5df1454df15b6a262d1028b/aa_modules/aamod_smooth.xml#L15-L17

But not with `aamod_realign`

https://github.com/automaticanalysis/automaticanalysis/blob/10b3425d2a99e294e5df1454df15b6a262d1028b/aa_modules/aamod_realign.xml#L47-L49

This difference stymies efficient usage of symlinks, because it forces to copy files instead of creating links, increasing analysis duration.

Thanks.

**Comment by tiborauer** [comment]
By default, every stream is considered to be "ismodified", meaning the input will be edited in place, and cannot be a link. This is the case for realign, which modifies the header of the input images.

Smoothing, on the other hand, only reads but does not edit the input (i.e., not "ismodified"); therefore, its input can be a link rather than a new copy.

**Comment by TamerGezici** [comment]
> By default, every stream is considered to be "ismodified", meaning the input will be edited in place, and cannot be a link. This is the case for realign, which modifies the header of the input images.
> 
> Smoothing, on the other hand, only reads but does not edit the input (i.e., not "ismodified"); therefore, its input can be a link rather than a new copy.

Ah ok, I see now. I did not know that the header of the input image was modified. 

Thanks.

**Comment by tiborauer** [comment]
That is what the "estimate only" is doing, so you do not have to reslice if you want to minimise the number of interpolations.
